export const INIT_STUDENTS                    = "INIT_STUDENTS"
export const SHOW_STUDENT                     = "SHOW_STUDENT"
export const ADD_STUDENT                      = "ADD_STUDENT"
export const UPDATE_STUDENT                   = "UPDATE_STUDENT"
export const DELETE_STUDENT                   = "DELETE_STUDENT"
