export default {
  SHOW_STUDENT: "SHOW_STUDENT",
  ADD_STUDENT: "ADD_STUDENT",
  UPDATE_STUDENT: "UPDATE_STUDENT",
  DELETE_STUDENT: "DELETE_STUDENT",

  // INCREMENT_NEXT_STUDENT_ID: "INCREMENT_NEXT_STUDENT_ID",
}
