export const INIT_STUDENTS = "INIT_STUDENTS"
export const SHOW_STUDENT = "SHOW_STUDENT"
export const ADD_NEW_STUDENT = "ADD_STUDENT"
export const UPDATE_STUDENT = "UPDATE_STUDENT"
export const UPDATE_STUDENTS = "UPDATE_STUDENTS"
export const DELETE_STUDENT = "DELETE_STUDENT"

export const SET_CURRENT_STUDENT = "SET_CURRENT_STUDENT"

export const INCREMENT_NEXT_STUDENT_ID = "INCREMENT_NEXT_STUDENT_ID"

export const UPDATE_NEW_STUDENT_FORM = "UPDATE_NEW_STUDENT_FORM"
